# Generated by Django 4.2.7 on 2023-12-02 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('category', models.CharField(max_length=50)),
                ('quantity', models.PositiveIntegerField()),
                ('unit_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('supplier_name', models.CharField(max_length=255)),
                ('supplier_contact', models.CharField(max_length=255)),
                ('reorder_point', models.PositiveIntegerField()),
                ('expiration_date', models.DateField()),
                ('location', models.CharField(choices=[('Section1', 'Section 1'), ('Section2', 'Section 2'), ('Section3', 'Section 3'), ('Section4', 'Section 4'), ('Section5', 'Section 5'), ('Section6', 'Section 6'), ('Section7', 'Section 7'), ('Section8', 'Section 8')], max_length=10)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('criticality_level', models.CharField(blank=True, choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], max_length=20, null=True)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Out of Stock', 'Out of Stock'), ('Reorder', 'Reorder')], max_length=20)),
            ],
        ),
    ]
